apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops
  labels:
    app: mlops
    component: secrets
type: Opaque
data:
  # Base64 encoded values (replace with actual values)
  # Example: echo -n "your-secret-value" | base64
  
  # MLflow credentials (if using remote tracking)
  MLFLOW_TRACKING_USERNAME: "bWxvcHMtdXNlcg=="  # mlops-user
  MLFLOW_TRACKING_PASSWORD: "bWxvcHMtcGFzc3dvcmQ="  # mlops-password
  
  # Database credentials (if using external MLflow backend)
  MLFLOW_DB_USERNAME: "bWxmbG93"  # mlflow
  MLFLOW_DB_PASSWORD: "bWxmbG93LXBhc3N3b3Jk"  # mlflow-password
  
  # API keys (if using external services)
  MLOPS_API_KEY: "bWxvcHMtYXBpLWtleQ=="  # mlops-api-key
  
  # Model registry credentials
  MLOPS_REGISTRY_TOKEN: "bWxvcHMtdG9rZW4="  # mlops-token
  
  # Monitoring credentials
  MLOPS_MONITORING_KEY: "bW9uaXRvcmluZy1rZXk="  # monitoring-key
  
  # Backup credentials
  MLOPS_BACKUP_KEY: "YmFja3VwLWtleQ=="  # backup-key
  
  # SSL certificates (if using HTTPS)
  MLOPS_SSL_CERT: ""  # Add your SSL certificate
  MLOPS_SSL_KEY: ""   # Add your SSL private key
  
  # SSH keys (if using Git-based model storage)
  MLOPS_SSH_PRIVATE_KEY: ""  # Add your SSH private key
  MLOPS_SSH_PUBLIC_KEY: ""   # Add your SSH public key
  
  # Docker registry credentials
  DOCKER_REGISTRY_USERNAME: "bWxvcHMtdXNlcg=="  # mlops-user
  DOCKER_REGISTRY_PASSWORD: "bWxvcHMtcGFzc3dvcmQ="  # mlops-password
  
  # Kubernetes service account token (auto-generated)
  KUBERNETES_SERVICE_ACCOUNT_TOKEN: ""
  
  # Custom environment variables
  MLOPS_CUSTOM_SECRET: "Y3VzdG9tLXNlY3JldC12YWx1ZQ=="  # custom-secret-value
