name: Contribution Heartbeat

on:
  workflow_dispatch:
  schedule:
    # Daily at 17:00 UTC (adjust if desired; contributions are recorded in UTC)
    - cron: "0 17 * * *"

permissions:
  contents: write

concurrency:
  group: contrib-heartbeat-${{ github.ref }}
  cancel-in-progress: false

jobs:
  heartbeat:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check for PAT secret
        id: has_pat
        run: |
          if [ -z "${{ secrets.PAT_FOR_CONTRIB }}" ]; then
            echo "present=false" >> $GITHUB_OUTPUT
          else
            echo "present=true" >> $GITHUB_OUTPUT
          fi

      - name: Checkout (no bot creds)
        if: steps.has_pat.outputs.present == 'true'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure author
        if: steps.has_pat.outputs.present == 'true'
        run: |
          git config user.name "CoelhoNunes"
          git config user.email "coelhonunes@users.noreply.github.com"

      - name: Update heartbeat file
        if: steps.has_pat.outputs.present == 'true'
        run: |
          mkdir -p .github
          printf "last_heartbeat_utc=%s\n" "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > .github/_last_heartbeat
          git add .github/_last_heartbeat
          if git diff --cached --quiet; then
            echo "No change; nothing to commit."
            exit 0
          fi
          git commit -m "chore(contrib): heartbeat [skip ci]"
      
      - name: Push commit to main
        if: steps.has_pat.outputs.present == 'true'
        env:
          PAT_FOR_CONTRIB: ${{ secrets.PAT_FOR_CONTRIB }}
        run: |
          git push https://x-access-token:${PAT_FOR_CONTRIB}@github.com/${{ github.repository }} HEAD:main

      - name: Summary when PAT missing
        if: steps.has_pat.outputs.present != 'true'
        run: echo "PAT_FOR_CONTRIB not set; skipping heartbeat without failing."
